baseURL: "http://ammarfarhan.github.io/"
languageCode: "en-us"
title: "Ammar - Data Analyst Portfolio Site"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 6
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
    # - identifier: projects
    #   name: Projects
    #   title: Data Analytics Projects
    #   url: /projects
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: Portfolio
    #   url: /portfolio
    #   parent: Projects
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "ahanaki"
  description: Ammar - Data Analyst Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "ahanaki" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ammar."
    subtitle: "I extract valuable insights from data to help you make informed decisions."
    # content: |-
    #   As an enthusiastic data analyst with a strong drive to learn, I have a comprehensive grasp of the essential tools necessary for effective data analysis, 
    #   including SQL, spreadsheets, Tableau, and Python. I am proficient in utilizing these tools in a creative way to extract valuable insights from complex data sets, 
    #   empowering data-driven decision-making.
    image: /images/me-square.jpg
    roundImage: true
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1-zooqWJPa7KqckDWlbpf-ejBc5Nk22nu/view?usp=share_link"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ahanaki/
        - icon: fab fa-instagram
          url: https://www.instagram.com/ahanaki_/
      customIcons:
        - icon: /images/tableau-icon.svg
          url: "https://public.tableau.com/app/profile/ahanaki"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me-square.jpg"
    content: |-
      As an enthusiastic data analyst with a strong drive to learn, I have a comprehensive grasp of the essential tools necessary for effective data analysis, 
      including SQL, spreadsheets, Tableau, and Python. 
      
      I am proficient in utilizing these tools in a creative way to extract valuable insights from complex data sets, empowering data-driven decision-making.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Excel (Spreadsheet)"
        - "SQL"
        - "Python"
        - "Tableau"
        - "Google Data Studio (Looker Studio)"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Entry Operator"
        company: "SD NEGERI BARENG 3"
        companyUrl: "https://www.facebook.com/sdnbareng3malang/"
        date: "Feb 2020 - Dec 2021"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a data entry operator for more than one year in SD NEGERI BARENG 3 MALANG.
        content: |
          SD NEGERI BARENG 3 is a public elementary school in Malang, Indonesia.
          - Managed -+ 500 students, 30 employees & lots of school data in the National Education Database, DAPODIK.
          - Cleaned 98% of the school data in the database, such as incomplete & incorrect student data.
          - Scanned documents and saved them in the database to keep records of essential organizational information.
          - Verified data files prior to entry to maintain high data accuracy.
          - Completed data entry tasks with accuracy and efficiency.

      - job: "Frontend Web Developer"
        company: "EzyIndustries"
        companyUrl: "https://ezyindustries.id/"
        date: "Nov 2017 - Nov 2018"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a frontend web developer for around one year in EzyIndustries.
        content: |
          EzyIndustries is an Information Technology & Business startup company in Malang, Indonesia.
          - Prioritized and problem-solved several tasks concurrently with minimum supervision.
          - Worked closely with developers on creating new code.
          - Adapted quickly to a constantly changing, deadline-driven environment.
          - Collaborated with in-house web designers to create sleek and innovative UI designs.

      
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: true
    items:
      - title: "Data Analytics"
        school:
          name: "RevoU"
          url: "https://revou.co/"
        date: "Jan 2023 - Apr 2023"
        GPA: "63/63 (100%)"
        content: |-
          Intensive data analytics program with <10% admission rate and weekly learning commitment of 15 to 20 hours, learning the fundamentals of data analytics, understanding business problems, statistics, data exploration, SQL, Python, data visualization, and data communication.
          - One of the top students in the class (58 students).
          - **Winner of the Python Competition** - conducted a customer segmentation and provided suitable thematic campaigns for each segment. Also conducted a benefit-cost analysis considering the allocated budget and specific target segments.
        featuredLink:
          enable: true
          name: "Certificate"
          url: "https://certificates.revou.co/ammar-farhan-nur-hakim-certificate-completion-fsda21.pdf"
      - title: "High School - Software Engineering Major"
        school:
          name: "SMK Negeri 4 Malang"
          url: "https://smkn4malang.sch.id/"
        date: "Jul 2016 - Jun 2019"
        GPA: "88/100"
        content: |-
          Participated in several IT competitions on behalf of the school from regional to international level.
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: SQL (Advanced)
        content: Issued by HackerRank in May 2023.
        url: https://www.hackerrank.com/certificates/a8bdc6596d59
      - title: Full Stack Data Analytics
        content: Issued by RevoU in April 2023.
        url: https://certificates.revou.co/ammar-farhan-nur-hakim-certificate-completion-fsda21.pdf
      - title: Machine Learning Basic
        content: Issued by Baparekraf Digital Talent & Dicoding in Nov 2022.
        url: https://drive.google.com/file/d/1I2adMirCHthS_zJAQ2Zec0eYZTII0yKe/view
      - title: Google Data Analytics Specialization
        content: Issued by Coursera in Oct 2022.
        url: "https://www.coursera.org/account/accomplishments/specialization/certificate/NS9VYYVV2QDL"

  # projects
  projects:
    enable: true
    btnName: Redirect to projects page
    url: /projects
    # title: "Custom Name"
    # items:
    #   - title: Hugo Profile
    #     content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile.png
    #     featured:
    #       name: Demo
    #       link: https://hugo-profile.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fa fa-envelope
    #         url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/hugo-profile
    #       - icon: fab fa-twitter
    #         url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

    #   - title: Image Converter
    #     content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
    #     image: /images/projects/converter.jpg
    #     featured:
    #       name: Demo
    #       link: https://django-converter.herokuapp.com
    #     badges:
    #       - "Django"
    #       - "Bootstrap"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/converter

    #   - title: Hugo Profile V2
    #     content: A clean and simple Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile2.jpg
    #     featured:
    #       name: Demo V2
    #       link: https://hugo-profile-2.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: afarhan.job@gmail.com
    btnName: Mail me
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xeqwddzy # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "projects"
      count: 3
      title: Recent Projects
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      # github: https://github.com
      linkedin: https://linkedin.com/in/ahanaki
      # twitter: https://twitter.com
      instagram: https://instagram.com/ahanaki_
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
